### ISSUE TITLE
panic: close of closed channel on interrupt

### ISSUE THREAD

**Issue by tuxcanfly** [btcsuite/btcsim#94]
panic: close of closed channel

    goroutine 10015 [running]:
    main.func·003()
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcsim/comm.go:587 +0x6a
    created by main.(*Communication).Communicate
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcsim/comm.go:589 +0xcaf

**Comment by stormasm** [comment]
I have seen this as well...

Thanks for adding this as an issue.

Michael Angerman
Corvallis, Oregon
